### ISSUE TITLE
i cannot not get rates - laravel 5.1

### ISSUE THREAD

**Issue by josiahke** [florianv/laravel-swap#49] opened 2018-05-10 06:49 UTC
ChainException in Chain.php line 66:
The chain resulted in 3 exception(s):
Exchanger\Exception\Exception: The current subscription plan does not support this API endpoint.
ErrorException: Undefined offset: 0
RuntimeException: Unable to parse XML data: String could not be parsed as XML

**Comment by florianv** [comment] 2018-05-10 07:19
Hey, can you please show me your config and which rate you are trying to get ?

**Comment by philperusse** [comment] 2018-05-10 15:18
This comes from fixer.io. 
They seem to have changed plans and the free tier does not permit to have a base currency.

Steps to reproduce : 

`http://data.fixer.io/api/latest?base=USD&access_key=[access-key]`

Reponse : 

`{"success":false,"error":{"code":105,"type":"base_currency_access_restricted"}}`

I think a fix could be to fetch all currencies and do the math in the service instead of leverging Fixer to do it.  I am currently working on this fix.

**Comment by florianv** [comment] 2018-05-11 06:20
Hey,

well this issue is not a Swap issue so I'm closing it.

@philperusse We could support that but it would have to be an add-on to all services, since the rates won't be "exact rates". You will see there is always a slight difference between the direct rates and the rates deduced from calculations.

**Closed as completed by florianv** 2018-05-11 06:20 UTC
